name: Docker Build and Push

on:
  schedule:
    - cron: "0 9 * * 3" # Wednesday 9 AM
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile-tor
          platforms: linux/arm64,linux/amd64,linux/arm/v7
          push: true
          tags: shrirajhegde/i2pd-tor:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
